### ISSUE TITLE
Player and outfit counts look wonky on mobile

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/website#467]
When there's a decent number of players, the player counts look super out of place. It needs a mobile layout tidyup, possibly putting the player count label its own line below the numbers. ![image](https://user-images.githubusercontent.com/1776058/181864722-23f022ef-90b5-4ef1-a993-0d409c032fea.jpeg)

**Comment by oslohes123** [comment]
This is how it is 
![image](https://user-images.githubusercontent.com/61867169/182244493-4c60cebb-38bd-422a-836c-63bfffa8f6a4.png)
And without all the stuff in the middle 
![image](https://user-images.githubusercontent.com/61867169/182244517-6ad4e7df-a896-4202-ba9b-53c958292fe3.png)

**Comment by oslohes123** [comment]
So yeah I was asking if whether I could just make the 12 columns in the row of the

**Comment by oslohes123** [comment]
Or maybe a simpler version may be 
![image](https://user-images.githubusercontent.com/61867169/182245632-f25e50e5-622a-462d-ba00-d2ea1438d5db.png)
This is on Iphone SE which has a very small x-axis
![image](https://user-images.githubusercontent.com/61867169/182245705-a8d2c8ac-edab-4611-9151-c61ec11a53fb.png)
Looks much nicer on a larger phone where the whole line is visible
And on ipad
![image](https://user-images.githubusercontent.com/61867169/182245792-76447c4e-e222-440e-ac5f-6f37f69b57b9.png)
And then on PC it looks fine
![image](https://user-images.githubusercontent.com/61867169/182245875-ba05272f-91a0-4ac5-9b38-bfba31a537ec.png)
Also this reduces the code complexity a bit since no breakpoints are needed as these are the same styles that are themselves adapting to the size of the display
